// ============================================================================
// ANNOTATED COPY — do not edit this file; edit MainActivityTest.kt instead.
// Original: ./MainActivityTest.kt (45 lines).
// ============================================================================
//
// What this file does:
//   Three unit tests that each spin up a fake Android runtime (via
//   Robolectric), launch MainActivity, and check something about the UI.
//   These tests run on the JVM — no phone, no emulator required.
//
// Kotlin syntax used in this file (quick reference):
//   @RunWith(X::class)    — class-level annotation. `X::class` is Kotlin's
//                           way to write "the Class object for X". It's a
//                           `KClass` (Kotlin's class reference), which JUnit
//                           expects here.
//   X::class.java         — converts a Kotlin `KClass` to a Java `Class<?>`.
//                           Many Android/Java APIs want the Java form, so
//                           you'll see this pattern a LOT in Kotlin+Android
//                           code. Read it as "the Java Class of X".
//   findViewById<TextView>(...) — method call with a generic type parameter
//                           supplied in angle brackets AFTER the method
//                           name. This tells the compiler "expect a TextView
//                           back" so you don't have to cast the return value.
//   val x = ...           — `val` is an immutable local variable (can't
//                           reassign). Kotlin infers the type from the
//                           right-hand side; you don't have to declare it.
//   .text.toString()      — method chaining. Reading a property (`.text`)
//                           then calling a method (`.toString()`) on it.
//
// JUnit / Robolectric concepts used here:
//   @RunWith(RobolectricTestRunner::class) — JUnit annotation that tells the
//                           test framework "use this custom test runner".
//                           Robolectric's runner rewrites Android framework
//                           classes on the fly so they run in plain JVM.
//   @Test                 — marks a method as a test. JUnit discovers it and
//                           runs it automatically. Must be `public` and
//                           return nothing (Kotlin's `fun ...()` without a
//                           return type returns `Unit`, which is JUnit-OK).
//   Robolectric.buildActivity(Class).create().get()
//                         — three chained calls that together simulate the
//                           "Android just launched this Activity" moment:
//                             1. buildActivity() — create an ActivityController.
//                             2. .create()        — call the Activity's onCreate.
//                             3. .get()           — hand back the Activity.
//                           After this, you have a MainActivity whose
//                           onCreate has already run.
//   findViewById<T>(id)   — walk the view tree looking for a View with that
//                           XML id. Here the id `R.id.hello_text` came from
//                           `android:id="@+id/hello_text"` in activity_main.xml.
//   assertEquals(expected, actual) / assertNotNull(msg, obj)
//                         — standard JUnit assertions. They throw
//                           AssertionError if the check fails; that signals
//                           "test failed" to the runner.
// ============================================================================

package com.without.hellosmoke

import android.widget.TextView
// JUnit 4's static assertion helpers. In Kotlin, Java statics are imported
// as if they were top-level functions.
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
// `@Test` marker annotation. Used below to tag each test method.
import org.junit.Test
// `@RunWith` class-level annotation.
import org.junit.runner.RunWith
// Robolectric's factory for building activities in a simulated environment.
import org.robolectric.Robolectric
// Robolectric's JUnit runner.
import org.robolectric.RobolectricTestRunner

/**
 * Unit tests for [MainActivity].
 *
 * The KDoc `[MainActivity]` syntax is a doc-link: IDEs turn it into a
 * clickable reference. The `spec:` lines tie each test to a requirement ID.
 *
 * Spec coverage:
 *  - HELLO-001 (ui_interaction): hello_text TextView shows "Hello"
 *  - HELLO-002 (lifecycle): onCreate completes; hello_text is non-null
 *  - HELLO-INV-001 (invariant): string resource hello_message == "Hello" exactly
 */
// This annotation applies to the CLASS, not the methods. It tells JUnit
// "run my tests using RobolectricTestRunner instead of the default runner".
// RobolectricTestRunner is what makes Android APIs work in a plain JVM test.
@RunWith(RobolectricTestRunner::class)
class MainActivityTest {

    // spec: HELLO-002
    // `@Test` above a function = "JUnit, run this as a test case".
    // Each @Test method runs independently with fresh state.
    @Test
    fun onCreate_inflatesLayoutAndFindsHelloTextView() {
        // `val activity = ...` — declare + assign. Kotlin infers the type
        // as MainActivity from the right-hand side.
        //
        // The chain below simulates the Android OS launching the activity:
        //   Robolectric.buildActivity(MainActivity::class.java)
        //     -> creates an ActivityController<MainActivity>
        //   .create()
        //     -> calls activity.onCreate(null) under the hood
        //   .get()
        //     -> returns the actual MainActivity instance, post-onCreate
        //
        // `MainActivity::class.java` is the Kotlin way of writing the Java
        // expression `MainActivity.class` (since Robolectric expects a Java
        // Class<?>, not a Kotlin KClass).
        val activity = Robolectric.buildActivity(MainActivity::class.java).create().get()

        // `findViewById<TextView>(R.id.hello_text)` — look up the view with
        // the XML id `hello_text`. The `<TextView>` tells Kotlin "I expect
        // this to be a TextView", so the returned type is `TextView?` (note
        // it's nullable — the id might not exist in the layout).
        //
        // In Java this would be `(TextView) activity.findViewById(R.id.hello_text)`
        // — note Java's cast in parens goes in front, Kotlin's generic goes
        // in angle brackets after the method name.
        val textView = activity.findViewById<TextView>(R.id.hello_text)

        // Two-arg assertNotNull: first is a failure message shown if the
        // check fails, second is the value to check. Here we're proving
        // that onCreate actually inflated the layout (if it hadn't, the
        // TextView wouldn't exist).
        assertNotNull("hello_text must be present after onCreate", textView)
    }

    // spec: HELLO-001
    @Test
    fun helloText_displaysHelloString() {
        val activity = Robolectric.buildActivity(MainActivity::class.java).create().get()
        val textView = activity.findViewById<TextView>(R.id.hello_text)

        // `textView.text` — reads the TextView's text property. Kotlin
        // property syntax: under the hood this calls `getText()` on the
        // Java class, but Kotlin lets you omit the `get/set` boilerplate.
        // `.toString()` — the text property's type is `CharSequence` (a
        // more general interface than String), so we normalize to String
        // before comparing — assertEquals compares by .equals(), and
        // `"Hello".equals(someCharSequence)` may return false even when
        // the characters match. Converting with toString() is the safe habit.
        assertEquals("Hello", textView.text.toString())
    }

    // spec: HELLO-INV-001
    @Test
    fun helloMessageStringResource_isExactlyHello() {
        val activity = Robolectric.buildActivity(MainActivity::class.java).create().get()

        // `activity.getString(R.string.hello_message)` — Android helper
        // that resolves a string resource ID to its actual text. The value
        // comes from `res/values/strings.xml`:
        //     <string name="hello_message">Hello</string>
        // So this returns "Hello" on first launch.
        val value = activity.getString(R.string.hello_message)
        assertEquals("Hello", value)
    }

    // NOTE: These three tests each build a fresh Activity. That's wasteful
    // but safe — no shared state between tests. In larger suites you'd
    // extract the setup into a `@Before` method. For 3 tests, it's fine.
}
