// ============================================================================
// ANNOTATED COPY — do not edit this file; edit MainActivity.kt instead.
// Original: ./MainActivity.kt (17 lines). Annotations target a junior dev who
// reads code fine but is new to Kotlin and the Android framework.
// ============================================================================
//
// What this file does:
//   Defines the one and only screen of the app. When the user taps the icon,
//   Android creates an instance of this class and calls onCreate(). onCreate
//   loads the XML layout (activity_main.xml), which contains the "Hello"
//   TextView. After that, the class does nothing else — the OS drives the
//   rest of the lifecycle.
//
// Kotlin syntax used in this file (quick reference):
//   package x.y.z     — like Java. Names the directory the file lives in.
//   import a.b.C      — pull type C into scope so you don't have to write a.b.C.
//   class Foo : Bar() — "Foo extends Bar". The PARENS `()` call Bar's
//                       no-arg constructor — Kotlin requires you to invoke
//                       the superclass constructor right there in the header.
//                       (In Java you'd call super() inside the constructor body.)
//   override fun ...  — `fun` is Kotlin's "function" keyword. `override` is
//                       mandatory when overriding a parent's method — the
//                       compiler will error if the parent has no such method.
//   Bundle?           — the `?` means "Bundle OR null". In Kotlin, a regular
//                       `Bundle` CANNOT be null; you'd get a compiler error
//                       if you tried. The `?` opts in to allowing null.
//   super.foo(...)    — call the parent class's version of the method.
//                       Same meaning as Java's `super.foo(...)`.
//
// Android framework concepts used here:
//   Activity          — one screen of an Android app. Lifecycle methods
//                       (onCreate, onStart, onResume, onPause, onStop,
//                       onDestroy) are hooks the OS calls on you in order.
//                       You only override the ones you care about.
//   onCreate(Bundle?) — the FIRST lifecycle hook. Called once, when Android
//                       is building your screen. Do your one-time setup here
//                       (load layout, find views, wire up listeners).
//   Bundle            — a key-value bag of saved state. Android passes it in
//                       if it's restoring your activity (e.g., after screen
//                       rotation or low-memory kill). It's `null` on a fresh
//                       cold start — which is why the parameter type is `Bundle?`.
//   setContentView(id)— "make this XML layout the content of my screen".
//                       Android reads the XML file, creates View objects for
//                       every tag (LinearLayout, TextView, ...), and attaches
//                       them to the screen.
//   R.layout.*        — `R` is a class the BUILD generates (you never write
//                       it). It contains integer IDs for every resource —
//                       layouts, strings, drawables. `R.layout.activity_main`
//                       is the int ID for `res/layout/activity_main.xml`.
//                       Android APIs take these ints, not file paths.
// ============================================================================

// `package` must match the directory path under src/main/java/.
// Files in the same package can see each other's package-private members
// without importing. Other packages import by this path.
package com.without.hellosmoke

// `android.app.Activity` is the OLD base class (since Android 1.0). Most
// modern apps use AndroidX's `AppCompatActivity` instead, which backports
// newer features to older Android versions. This smoke test uses the bare
// `Activity` because it's the minimum viable thing that compiles.
import android.app.Activity
// `Bundle` is the saved-state container. Imported so we can declare the
// onCreate parameter type without writing the full `android.os.Bundle`.
import android.os.Bundle

/**
 * Single-screen Hello activity.
 *
 * The /** ... */ block above is a KDoc comment — Kotlin's equivalent of
 * Javadoc. Tools (IDE, Dokka) pick it up for hover-help and generated docs.
 * The `// spec:` lines are a team convention here: each one traces this
 * class to a requirement ID in .spec/hello-screen.spec.yml.
 *
 * // spec: HELLO-001 — displays TextView with text "Hello" on first launch
 * // spec: HELLO-002 — onCreate inflates content view without throwing
 */
// `class MainActivity : Activity()` — declares a class named MainActivity
// that inherits from Activity. The trailing `()` calls Activity's no-arg
// constructor. Without those parens the code would not compile.
class MainActivity : Activity() {

    // `override fun onCreate(...)` — overrides the parent's onCreate.
    // `override` is REQUIRED in Kotlin (unlike Java's optional @Override).
    // `savedInstanceState: Bundle?` — parameter name BEFORE its type, with
    // a colon. The `?` makes it nullable (it's null on cold start).
    override fun onCreate(savedInstanceState: Bundle?) {
        // Always call super.onCreate FIRST in Activity subclasses. The
        // Activity base class does critical bookkeeping (restoring state,
        // wiring up the window, etc.) that your code depends on. Forgetting
        // this call crashes at runtime with a clear error message.
        super.onCreate(savedInstanceState)

        // Load the XML layout as this screen's content. Android parses
        // activity_main.xml, builds the view tree (a LinearLayout containing
        // a TextView), and attaches it to the Activity's window.
        // After this line returns, the "Hello" text is onscreen-ready (it
        // will actually paint when the OS hits the `onResume` lifecycle hook).
        setContentView(R.layout.activity_main)

        // NOTE: there's no `onDestroy`, `onPause`, etc. overridden here.
        // That's fine — the defaults from `Activity` do the right thing.
        // Only override lifecycle hooks when you have code to run in them.
    }
}
